### PR TITLE
Adding translate and opacity aliases

### PR DESCRIPTION
**Pull request by gersak**
Hi,

Pull request extends aliases.edn with translate, scale, skew, rotate, opacity declarations

More important is change to the __build.cljc__ file that extends ```[:alias-groups :color]``` so that color aliases are extended to fill and stroke and usable with svg elements.

### CODE REVIEW

**Comment by thheller** [comment]
I don't think this will actually work? Currently when a style attribute is repeated the latter will override prior values.

`(css :rotate-180 :translate-x-4)` would end up as `transform: translateX(1rem)`. There is no inteherent merging of values, and since both just use `:transform` they just overwrite.

I always found `(css {:transform "rotate(180deg) translateX(1rem)"})` sufficient to not bother with aliases?

I'm not opposed to adding support for merging, but have not thought about how to do so in a proper way.

**Comment by gersak** [comment]
I see… That approach is better and cleaner.

I haven't used much of transform aliases, but I do use :opacity aliases occasionally. Would it be OK to exclude "transform" aliases since transform is composable and to open new PR for :opacity and :origin-transform?

Lastly, would you approve the proposed changes to the build.cljc file?

**Comment by thheller** [comment]
`build.cljc` seems fine. Just remove `:transform` from this PR, or make a new one.

**Comment by gersak** [comment]
Thanks, I'll open new PR

**Pull request closed without merging**
